import React from "react";

export const metadata = {
    title: 'Branding | Contact',
    description: 'Generated by create next app',
};

export default function Contact() {
    return(
        <div>
            <h1>Contact</h1>
            <p>This is the Contact</p>
        </div>
    )
}