import React from 'react'

export const metadata = {
    title: 'Partner | Technical Support',
    description: 'Generated by create next app',
};

const TechicalSupportPage = () => {
    return (
        <div>
            <h1>TechicalSupportPage</h1>
            <p>This is the page component</p>
        </div>
    )
}

export default TechicalSupportPage
