import React from 'react'

export const metadata = {
    title: 'Partner | Price Support',
    description: 'Generated by create next app',
};

const PriceSupportpage = () => {
    return (
        <div>
            <h1>Page</h1>
            <p>This is the page component</p>
        </div>
    )
}

export default PriceSupportpage
