import React from 'react'

export const metadata = {
    title: 'Partner | Home',
    description: 'Generated by create next app',
};

const HomePartnerpage = () => {
    return (
        <div>
            <h1>Home Partner</h1>
            <p>This is the page component</p>
        </div>
    )
}

export default HomePartnerpage
