import React from "react";

export const metadata = {
    title: 'Branding | Home',
    description: 'Generated by create next app',
};

export default function Home() {
    return(
        <div>
            <h1>Home</h1>
            <p>P BAIM</p>
        </div>
    )
}