import React from "react";

export const metadata = {
    title: 'Branding | Footer',
    description: 'Generated by create next app',
};

export default function Footer() {
    return(
        <div>
            <h1>Footer</h1>
            <p>This is the Footer</p>
        </div>
    )
}