import Image from "next/image";
import React from "react";

export const metadata = {
  title: 'Xion1 CMS',
  description: 'Generated by create next app',
};
export default function App() {
  return (
    <p>Hello</p>
  );
}
