import React from 'react'

export const metadata = {
    title: 'Partner | History Support',
    description: 'Generated by create next app',
};

const HistorySupport = () => {
    return (
        <div>
            <h1>kepo</h1>
            <p>This is the e component</p>
        </div>
    )
}

export default HistorySupport
