import React from 'react'

export const metadata = {
    title: 'Partner | Register Deal',
    description: 'Generated by create next app',
};

const RegisterDealpage = () => {
    return (
        <div>
            <h1>Register Deal Page</h1>
            <p>This is the Register Deal Page</p>
        </div>
    )
}

export default RegisterDealpage
