import React from 'react';

export const metadata = {
    title: 'Branding',
    description: 'Generated by create next app',
};

const BrandingPage = () => {
    return (
        <>
        <span className="font-bold text-4xl">Branding</span>

        <div className="border-dashed border border-zinc-500 w-full h-12 rounded-lg"></div>
        <div className="border-dashed border border-zinc-500 w-full h-64 rounded-lg"></div>
        </>
    );
};

export default BrandingPage;
