import React from "react";

export const metadata = {
    title: 'Branding | Navigation',
    description: 'Generated by create next app',
};

export default function Navigation() {
    return(
        <div>
            <h1>Navigation</h1>
            <p>This is the Navigation</p>
        </div>
    )
}